### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by DGGua** [Planshit/Tai#94]
每天几乎都有崩溃

Error log如下：
```log
[ Tai Version ]  1.0.0.4;

[ WindowsOS Name ]  Microsoft Windows 11 专业版;

[ Screen Size ]  2560 × 1440;


++++++++++++++++++++++++++++++++++++++++++++++++++

中间略

[ Warn ] [ 2023-01-06 20:07:06 ] 
The path is not of a legal form. | Process Name:Idle | Process File: | Process Description:
[ Caller Info ] Line:99,File:Tai\Servicers\Instances\Observer.cs,name:Handle
------------------------

[ Info ] [ 2023-01-06 20:07:52 ] 
status:Wake,process:Thunder,seconds:9,start:1/6/2023 8:07:51 PM,end:1/6/2023 8:07:52 PM,time:1/6/2023 8:07:20 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------

[ Info ] [ 2023-01-06 20:08:13 ] 
status:Wake,process:PotPlayerMini64,seconds:7,start:1/6/2023 8:08:00 PM,end:1/6/2023 8:08:13 PM,time:1/6/2023 8:07:29 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------

[ Info ] [ 2023-01-06 20:08:39 ] 
status:Wake,process:explorer,seconds:4,start:1/6/2023 8:08:00 PM,end:1/6/2023 8:08:39 PM,time:1/6/2023 8:07:37 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------

[ Info ] [ 2023-01-06 20:09:04 ] 
status:Wake,process:Thunder,seconds:7,start:1/6/2023 8:08:00 PM,end:1/6/2023 8:09:04 PM,time:1/6/2023 8:07:41 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------

[ Info ] [ 2023-01-06 20:09:25 ] 
status:Wake,process:PotPlayerMini64,seconds:5,start:1/6/2023 8:08:00 PM,end:1/6/2023 8:09:25 PM,time:1/6/2023 8:07:51 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------

[ Info ] [ 2023-01-06 20:09:50 ] 
status:Wake,process:PotPlayerMini64,seconds:3,start:1/6/2023 8:08:00 PM,end:1/6/2023 8:09:50 PM,time:1/6/2023 8:07:57 PM
[ Caller Info ] Line:414,File:Tai\Servicers\Instances\Main.cs,name:UpdateTime
------------------------
[ Error ] [ 2023-01-06 20:10:13 ] 
[程序崩溃异常] System.Data.Entity.Core.EntityException: An error occurred while starting a transaction on the provider connection. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at System.Data.SQLite.SQLiteTransaction.Begin(Boolean deferredLock)
   at System.Data.SQLite.SQLiteTransactionBase..ctor(SQLiteConnection connection, Boolean deferredLock)
   at System.Data.SQLite.SQLiteTransaction..ctor(SQLiteConnection connection, Boolean deferredLock)
   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<>c.<BeginTransaction>b__4_0(DbConnection t, BeginTransactionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.BeginTransaction(DbConnection connection, BeginTransactionInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<>c__DisplayClass63_0.<BeginDbTransaction>b__0()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginTransaction()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at Core.Servicers.Instances.AppData.UpdateApp(AppModel app)
   at Core.Servicers.Instances.Main.IsCheckApp(String processName, String description, String file)
   at Core.Servicers.Instances.Main.Observer_OnAppActive(String processName, String description, String file)
   at Core.Event.ObserverEventHandler.Invoke(String processName, String description, String file)
   at Core.Servicers.Instances.Observer.EventInvoke(String processName, String description, String filename)
   at Core.Servicers.Instances.Observer.<Handle>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[ Caller Info ] Line:81,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------------------
```

不太清楚还需要提交什么，有其他信息需要我随时提供

**Comment by noberumotto** [comment]
提交的信息足够了，谢谢反馈

**Comment by DGGua** [comment]
更新到现在未出现问题
